### ISSUE TITLE
python 3.6 support possible?

### ISSUE THREAD

**Issue by darix** [openSUSE/obs-service-cargo_vendor#23]
would enable running it on leap/SLE

**Comment by Firstyear** [comment]
I haven't had a need to run it on leap/sle to this point, since all my running of the service has been from tumbleweed, and then we can commit sources for SLE/leap. What machines are you thinking to run this on? What's currently the blocker in regard to the design of the python that would need changes for 3.6?

**Comment by darix** [comment]
the container for the server side install is based on 15.5 right now. and your package does not build for it because of the buildrequires for python3 >= 3.8 :)

**Comment by Firstyear** [comment]
Fixed in master, I'll update the package too.

**Comment by darix** [comment]
Danke
