### ISSUE TITLE
include cargo check or cargo clippy runs

### ISSUE THREAD

**Issue by uncomfyhalomacro** [openSUSE/obs-service-cargo_vendor#57]
Sometimes, updating the lockfile and manifest file does not ensure that compilation is successful in OBS. Users should be notified before they push an update of the package.

**Comment by uncomfyhalomacro** [comment]
i guess `cargo check` should suffice since it won't make sense to use `cargo clippy` anyway.

**Comment by Firstyear** [comment]
We shouldn't do this, this is a spec/build issue, not a vendoring one. If the user does an update and it fails to build, that is something they need to check before they submit. 

We also can't do this because it may not be possible for the error to be apparent in the obs env, rather than the build env
