### ISSUE TITLE
document the --i-accept-the-risk in /usr/lib/obs/service/cargo_vendor.service

### ISSUE THREAD

**Issue by darix** [openSUSE/obs-service-cargo_vendor#68]
while I generally prefer to run audit I have one app atm where this is actually blocking me from deploying other important fixes.
in the past this was 2 services and i could disable it that way.

Edit:

in the mean time i found the --i-accept-the-risk option in the --help output. but it isnt documented in /usr/lib/obs/service/cargo_vendor.service

**Comment by Firstyear** [comment]
There is a reason it's not documented. We don't want people to just "pile in" risk accepts without knowing what they're for. It's always better to address the problem directly.

**Comment by darix** [comment]
At some point i will just stop packaging rust things.

**Comment by Firstyear** [comment]
Look. Rust in OpenSUSE is trying to do things that aren't done in other distros. This means I've spent a ton of time and work with our security teams to make sure that we can manage things properly and manage the threats and risks.

An important part of that is being about to run cargo-audit on our packages before they are committed. The same way we enforce AV scans before commits. The same way we embed custom rust library metadata in packages to allow post commit scans and issue assignment. The same way we have other osc pre-flight checks to gate packages to ensure quality and compliance. 

If we just plastered around "oh yeah heres how you can just bypass all the security checks" is that responsible? Is that something that we should be doing as ecosystem maintainers? No it absolutely isn't.

This is *WHY* we add hoops. WHY we raise that bar. We want people to *fix the problem*, to update their libraries, and to work with upstreams *if* security issues are there. And as an absolute last resort, if they absolutely can't possibly work out any possible other way around it and are 100% sure the issue doesn't affect them, then sure, we'll teach them on a case by case how to use the "risk accept". 

But advertising that on the front of the osc service as "OH YEAH, heres this way you can totes yolo bypass the safety control" is just going to ENCOURAGE people to do it. We already have some "contributors" who hate that we enforce cargo-audit at all. We have plenty of people who will just blindly copy paste it as a way to "get the package committed" without knowing the risks and reasons. 

The point is to *add friction* to doing the wrong thing, so that doing the *right thing* is the path of least resistance. We are intentionally making it harder to push people to do the secure thing.

So I'm sorry that our attitude and care for the rust ecosystem upsets you so much. There are reasons behind the decisions we make, that you may not have all the visibility into, and may not agree with. But my intent is to make sure that Rust has the best packaging ecosystem of any distro. I will not compromise on that.
